FROM node:20-alpine AS frontend

WORKDIR /frontend

COPY package*.json ./
RUN npm ci --silent

COPY . .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=frontend /frontend/dist /usr/share/nginx/html