FROM golang:1.21-alpine AS backend

WORKDIR /backend

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o bin/server ./cmd/main.go


FROM alpine:latest

WORKDIR /app

COPY --from=backend /backend/bin/server ./server

